"""add date_created to model

Revision ID: 7599d02857ce
Revises: 8c642cf44fb5
Create Date: 2022-02-18 14:59:06.820774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7599d02857ce'
down_revision = '8c642cf44fb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('date_created', sa.DateTime(), nullable=True))
    op.add_column('post', sa.Column('date_created', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'date_created')
    op.drop_column('comment', 'date_created')
    # ### end Alembic commands ###
