version: '3.8'

services:
    db:
        image: postgres:13-alpine
        env_file: .env
        logging:
            options:
                max-size: 10m
                max-file: "3"
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        ports:
            - "5432:5432"    
    arcu:
        build:
            context: ./
            dockerfile: Dockerfile
        env_file: .env
        depends_on:
            - db
        logging:
            options:
                max-size: 10m
                max-file: "3"
        ports:
            - "8800:80"
        restart: always

volumes:
    postgres_data:
